#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

# key bindings
sxhkd &

#rendering
# compton &
picom &

# panel
 tint2 &

# polybar
#  ~/.config/polybar/launch.sh  --grayblocks &

# below will set polybar to pywall colours
# bash ~/.config/polybar/grayblocks/scripts/pywal.sh ~/Pictures/Wallpaper/ &

# restore previous session pywall
# wal -R &
wal -i ~/Pictures/Wallpaper/ &

nm-applet &
blueman-applet &

blueman-manager &
pavucontrol &

telegram-desktop &
slack &
teams &


# telegram-desktop &
# slack &

# firefox &
# microsoft-edge-dev &
# urxvt -name "cmatrix" -hold -e cmatrix -ba &
# urxvt -name "sensors" -hold -e watch sensors &
# urxvt -name "mocp" -hold -e mocp &
 urxvt -name "btm" -hold -e btm &

# Set some bsp specific stuff

#if xrandr -q | grep 'DP-2 connected'; then
 #  xrandr --output DP-1 --mode 2560x1440
 #  xrandr --output DP-2 --mode 1680x1050 --left-of DP-1
 #  bspc monitor DP-2 -d VI VII VIII IX X
 #  bspc monitor DP-1 -d I II III IV V
  #  ~/.screenlayout/dual_dp.sh
#
#if xrandr -q | grep 'DP2 connected'; then
 #   xrandr --output DP2 --mode 1920x1080 --top-of eDP1
 #   bspc monitor eDP1 -d I II III IV V
 #   bspc monitor DP2 -d VI VII VIII IX X
 #   bspc monitor HDMI2 -d XI XII XIII XIV XV

#    ~/.screenlayout/home_dp.sh
#else
 #   bspc monitor DP-1 -d I II III IV V VI VII VIII IX X
 #   xrandr --output DP-1 --mode 2560x1440
#fi

bspc monitor DP-1 -d I II III IV V
bspc monitor DP-2 -d VI VII VIII IX X

  ~/.screenlayout/dual_dp2.sh

# xrandr --output DP-1 --mode 2560x1440
# xrandr --output DP-2 --mode 1680x1050


bspc config window_gap 12
bspc config border_width 2

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# bspwm rules

# bspc rule -a TelegramDesktop desktop=^2 follow=off
# bspc rule -a Slack desktop=^2 follow=off
# bspc rule -a Geany desktop=^4
# bspc rule -a mplayer2 state=floating
#bspc rule -a Microsoft-edge-dev desktop=^5
#bspc rule -a zoom desktop=^7 @state=floating rectangle=789x512+264+130
# bspc rule -a Pavucontrol desktop=^10 state=floating rectangle=789x512+264+130
# bspc rule -a blueman desktop=^7 state=floating rectangle=789x512+264+130
#bspc rule -a blueman desktop=^10
# bspc rule -a Pavucontrol desktop=^7
#bspc rule -a "URxvt:sensors" desktop=^4 follow=off
#bspc rule -a "URxvt:cmatrix" desktop=^4 follow=off
# bspc rule -a "URxvt:mocp" desktop=^4 follow=off
 bspc rule -a "URxvt:btm" desktop=^1 follow=off
 bspc rule -a "Pavucontrol" desktop=^1 follow=off
 bspc rule -a "blueman-manager" desktop=^1 follow=off
 bspc rule -a "Slack" desktop=^8 follow=off
 bspc rule -a "TelegramDesktop" desktop=^8 follow=off
 bspc rule -a "Microsoft Teams - Preview" desktop=^2 follow=off

#bspc monitor DP1 -g  1920x1080+0+0
#bspc monitor eDP1 -g 1920x1080+0+0
#bspc monitor HDMI2 -g 1920x1080i+0+0
